#!/bin/bash -e

root_dir=$(dirname $BASH_SOURCE[0])
will_exit=0

#
# First, check all the mandatory environment variables
#
for variable in \
  NEW_RELIC_LICENSE_KEY NEW_RELIC_LOG_LEVEL \
  MYSQL_HOST MYSQL_CATEGORIES MYSQL_USER MYSQL_PASS
do
  eval target=\$$variable
  if [ -z "${target}" ]; then
    echo "Must set $variable environment variable!"
    will_exit=1
  fi
done

if [ 0 -ne $will_exit ]; then
  echo "Exiting"
  exit $will_exit
fi

#
# Then create the config dir if needed and write the configs
#
mkdir -p "$root_dir/config/"

cat > "$root_dir/config/newrelic.json" <<EOF_JSON
{
  "license_key": "${NEW_RELIC_LICENSE_KEY}",
  "log_level": "${NEW_RELIC_LOG_LEVEL}",
  "log_file_name": "null",
  "log_file_path": "/dev"
}
EOF_JSON

cat > "$root_dir/config/plugin.json" <<EOF_JSON
{
  "agents": [
    {
      "name"    : "${MYSQL_HOST}",
      "host"    : "${MYSQL_HOST}",
      "metrics" : "${MYSQL_CATEGORIES}",
      "user"    : "${MYSQL_USER}",
      "passwd"  : "${MYSQL_PASS}"
    }
  ]
}
EOF_JSON
